export const FETCH_WEATHER_START = "MY_WEATHRE_FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "MY_WEATHRE_FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "MY_WEATHRE_FETCH_WEATHER_FAIL";

export const FETCH_WEATHER_EVERY3HOURS_START = "MY_WEATHRE_FETCH_WEATHER_EVERY3HOURS_START";
export const FETCH_WEATHER_EVERY3HOURS_SUCCESS = "MY_WEATHRE_FETCH_WEATHER_EVERY3HOURS_SUCCESS";
export const FETCH_WEATHER_EVERY3HOURS_FAIL = "MY_WEATHRE_FETCH_WEATHER_EVERY3HOURS_FAIL";

export const FETCH_FAVORITES_START = "MY_WEATHRE_FFETCH_FAVORITES_START";
export const FETCH_FAVORITES_SUCCESS = "MY_WEATHRE_FETCH_FAVORITES__SUCCESS";
export const FETCH_FAVORITES_FAIL = "MY_WEATHRE_FETCH_FAVORITES_FAIL";

